### ISSUE TITLE
ModuleNotFoundError: No module named 'fastai.models.resnext_50_32x4d'

### ISSUE THREAD

**Issue by votamvan** [prajjwal1/language-modelling#1]
Please tell me where i can find the module fastai.models.resnext_50_32x4d, thanks

**Comment by votamvan** [comment]
root@/opt/language-modelling# python ULMfit.py 
Traceback (most recent call last):
  File "ULMfit.py", line 7, in <module>
    &nbsp; from fastai.text import *
  File "/opt/language-modelling/fastai/text.py", line 1, in <module>
      &nbsp; from .core import *
  File "/opt/language-modelling/fastai/core.py", line 2, in <module>
     &nbsp; from .torch_imports import *
  File "/opt/language-modelling/fastai/torch_imports.py", line 13, in <module>
    &nbsp;  from .models.resnext_50_32x4d import resnext_50_32x4d
ModuleNotFoundError: No module named 'fastai.models.resnext_50_32x4d'

**Comment by NatLee** [comment]
You can get .py files here.
https://github.com/fastai/imagenet-fast/tree/master/imagenet_nv/models

But there are other problems in this repository.

**Comment by prajjwal1** [comment]
You can find them here https://github.com/fastai/imagenet-fast/tree/master/imagenet_nv/models
